### ISSUE TITLE
Avoid .sync() deleting certain files

### ISSUE THREAD

**Issue by sbalay** [pgherveou/gulp-awspublish#107]
Is it possible to use a regex or some kind of list so that sync does not delete certain files that are in the bucket but not in my local folder?

**Comment by sbalay** [comment]
My scenario is: I have a frontend project hosted in a bucket, mainly .js .css and .html files. All those files are uploaded using gulp-awspublish. On another project, I generate the sitemap.xml file for this web and upload it to the bucket. So, everytime I use awspublish to upload the code files, the sitemaps gets deleted.

**Comment by iongion** [comment]
Yes, me too, I deploy my sites and also have `/next-gen` , `/edge`, etc. aliases under the same bucket where I do A/B testing
Just a way to specify what sync should exclude, please!

**Comment by leog** [comment]
+1

**Comment by RichardOtvos** [comment]
Hey there!
It seems to be a pretty popular feature, so I will come up with something, on the API side. It would also be helpful to hear some ideas, from you, about how do you imagine using this (like in calls in your gulpfiles for example). 

If we have some consensus, I would be happy to make this PR for you guys! Of course if you have some existing code that you can submit, feel free to do so 😄

**Comment by sbalay** [comment]
@RichardOtvos Hey I've recently made a quick workaround for this, and I'm using it locally.
I'll check if the code can be improved, add some tests and submit a pull request.

**Comment by RichardOtvos** [comment]
Nice! It will be included in the next release, (which I will try to make it happen in the next few days)
