### ISSUE TITLE
Invalid semantic versioning + no tests for the new Publisher class

### ISSUE THREAD

**Issue by RichardOtvos** [pgherveou/gulp-awspublish#112]
Hi!

After the latest release the Publisher class also takes an options parameter, but as fas as I see there are no tests covering this functionality. 

This is also a new (backward compatible) feature which should mean you increment the Minor version in your package JSON. 

Our build broke, because the wrong version increase, which made me pretty sad. :(

If you need help I'm happy to update the tests for you in a pull request. Also feel free to reach out if you want to discuss this.

**Comment by pgherveou** [comment]
You are right. 
Sorry about this mistake,
I am happy to accept any pull request you want to contribute. 
I am not actively using this plugin, so I can add you on github/npm if you wish

**Comment by RichardOtvos** [comment]
Sure :)

Let me cook up the PR quickly. I'm also happy to help if you need help maintaining the library.

**Comment by pgherveou** [comment]
@RichardOtvos just added you as collaborator, let me know what your npm username is so I can add you there as well if you want to

**Comment by RichardOtvos** [comment]
Thanks, @pgherveou ! My npm username is richardotvos.
Thanks again!

**Comment by pgherveou** [comment]
great just added you
