### ISSUE TITLE
default 'public-read' canned ACL 

### ISSUE THREAD

**Issue by forrestbthomas** [pgherveou/gulp-awspublish#120]
Hi, 

Firstly, thank you so much for your work on this module. I use it all the time.

I'm wondering if there is a possibility of removing the default `public-read` canned ACL. I am using this module for a project and need to be able to specify grants instead of a canned ACL. AWS doesn't allow for specifying canned ACL's as well as grants, thus making this module no longer usable for me. I'd love to be able to continue using this module, however. Would a PR removing lines 304 and 305 of `index.js` be received or is there some reason for the default canned ACL that eludes me?

Cheers,
Forrest

**Comment by pgherveou** [comment]
Hi Thomas
Someone just wrote a pull request that we merged and publish to disable acl 
https://github.com/pgherveou/gulp-awspublish#publisherpublishheaders-options
Does this answer your use case?

**Comment by forrestbthomas** [comment]
Yep, sure does. Thanks!

**Comment by flodonsky** [comment]
@pgherveou this can be closed

**Comment by pgherveou** [comment]
Thkd
