### ISSUE TITLE
InvalidAccessKeyId

### ISSUE THREAD

**Issue by panvourtsis** [pgherveou/gulp-awspublish#121]
Hi all,

i am trying to connect to my bucket and although i am using this (DEMO keys etc) i am getting "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records."

I tried the credentials many times and are working through the client. Any ideas?

var publisher = awspublish.create({
        params: { Bucket: 'myBucket' },
        region: 'eu-west-1',
        accessKeyId: 'VXBNhyvNBSrqA0E8VfSH',
        secretAccessKey: 'A5H44QX7UTA'
    });

**Comment by panvourtsis** [comment]
anyone?

**Comment by michaelBenin** [comment]
Hey @panvourtsis ~

I would remove the your credentials from the thread above.

In the examples, using this with accesskey and id can be found here: 

https://github.com/pgherveou/gulp-awspublish/blob/master/lib/index.js#L205

As you can see you need to create an instance first from here:

https://github.com/pgherveou/gulp-awspublish/blob/master/examples/simple.js#L6

Here's the docs from AWS.s3 for providing a config:

http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html

**Comment by michaelBenin** [comment]
Also check the permissions on that bucket.
