### ISSUE TITLE
What is cacheOptions?

### ISSUE THREAD

**Issue by dagumak** [pgherveou/gulp-awspublish#127]
I don't understand why do I need to provide an option for this when creating a publisher.

> The cacheOptions object allows you to define the location of the cached hash digests. By default, they will be saved in your projects root folder in a hidden file called '.awspublish-' + 'name-of-your-bucket'.

Why do I need this? What does it do? Does S3 require me to have this? I don't understand why I need this extra file in my repository.

**Comment by pgherveou** [comment]
Nope its just part of the library, Its a local file where we store the hash digest of each file you pushed to s3 to avoid making a call to s3 api next time you run your gulp task

**Comment by dagumak** [comment]
@pgherveou Thanks!
