### ISSUE TITLE
CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by kaytrance** [pgherveou/gulp-awspublish#139]
My publisher object in `gulpfile.js` **have** credentials (here I have changed them, of course):
```
var publisher = awspublish.create({
      region: 'eu-west-1',
      params: {
         Bucket: 'my-bucket-name'
      },
      acccessKeyId:    "my-key-id-here",
      secretAccessKey: "my-secret-here"
   },
   {
      cacheFileName: '.cache'
      });
```

Why then I still receive this error?

**Comment by MichaelJCole** [comment]
See this PR: https://github.com/pgherveou/gulp-awspublish/pull/135/commits/c5ab23d9223378163df2fac11892d90ad063f6a3

**Comment by pioug** [comment]
It seems correct according to AWS SDK (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property). Feel free to reopen the issue with a reproducible case if possible.
