### ISSUE TITLE
How can I use option s3.path?

### ISSUE THREAD

**Issue by Daworks** [pgherveou/gulp-awspublish#140]
Hi!
This plugin is very convenient and great among the s3 related plugins I have used.

I want to specify the location when uploading to s3, but there is a s3.path option in the manual. I do not know how to use this. How do I set up to upload only certain directory and files within a bucket?

![screenshot](https://s3.ap-northeast-2.amazonaws.com/ssgblog/2017-07/capture.jpg)

Below is my gulpfile.js.

<pre>
gulp.task('upload', function(){

	var publisher = awspublish.create({
		region: 'ap-northeast-2',
		params: {
			Bucket: '***',
		},
		"accessKeyId": "***",
		"secretAccessKey": "***",
	});

	var headers = {
		'Cache-Control': 'max-age=315360000, no-transform, public',
	};

        var doc = 'waterski';

	return gulp.src('./2017-07/'+doc+'/**/*')
			.pipe(rename(function(path){
				path.dirname += '/2017-07/'+doc;
			}))
			.pipe(parallelize(publisher.publish(headers), 30))
			.pipe(awspublish.reporter({states: ['create', 'update', 'delete']}));
}); </pre>

**Comment by flodonsky** [comment]
Try: https://github.com/pgherveou/gulp-awspublish#rename-file--directory
