### ISSUE TITLE
README is a lie re: IAM credentials.

### ISSUE THREAD

**Issue by MichaelJCole** [pgherveou/gulp-awspublish#144]
Hey guys, thanks for this plugin.  I burned 4 hours on this problem:

The [README](https://github.com/pgherveou/gulp-awspublish#testing) shows one way to configure IAM credentials.  This way consistently results in ACCESS DENIED.  It may work sometimes depending on how your AWS client is logged in.

This [PR](https://github.com/pgherveou/gulp-awspublish/pull/135/commits/c5ab23d9223378163df2fac11892d90ad063f6a3) shows the correct way and gets rid of ACCESS DENIED.

**Comment by individual11** [comment]
thanks! was driving me crazy.

Can this pr be accepted?

**Comment by pioug** [comment]
Thank you for reporting this! The readme is updated https://github.com/pgherveou/gulp-awspublish/pull/148.

By the way, the `credentials` object is not always necessary based on [AWS.S3 documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property). I don't know well this SDK, but seems like it has something to do with setting `signatureVersion` in the same time.
