### ISSUE TITLE
what is "cacheFileName", "Cache-Control" where can I find doumentation on this?

### ISSUE THREAD

**Issue by MarlonCopeland** [pgherveou/gulp-awspublish#158]
what is "cacheFileName", "Cache-Control" where can I find doumentation on this? these options are not present on the AWS SDK documentation.

Will gulp awspublish work with this parameter not changed from 'your-chache-location'?

**Comment by pioug** [comment]
AFAIK, 
- `cacheFileName: 'your-cache-location'` is not an AWS thing
> https://github.com/pgherveou/gulp-awspublish#awspublishcreateawsconfig-cacheoptions
The cacheOptions object allows you to define the location of the cached hash digests. By default, they will be saved in your projects root folder in a hidden file called '.awspublish-' + 'name-of-your-bucket'.

- `Cache-Control` may be one of the HTTP headers that will be set for your assets

I hope it helps!
