### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by pioug** [pgherveou/gulp-awspublish#163]
Hello @pgherveou,

Can you enable Travis for this repo https://www.travis-ci.org/pgherveou/gulp-awspublish?

I would like to upgrade the dependencies so projects that use this plugin stop pulling old packages just  for `gulp-awspublish` needs 🏋️  I am afraid a lot of them may have dropped support for very old Node versions (and I think we should too).

Anyway, I would like to communicate clearly what Node versions are supported and make sure that things won't break by running tests on different Node. 

Similar to https://github.com/avajs/ava repository:
https://github.com/avajs/ava/blob/master/.travis.yml#L2-L5
https://github.com/avajs/ava/blob/master/package.json#L9-L11

Not to mention that automated tests are also useful for contributors.

We can run the tests with my AWS account for now 🙈 Eventually we can consider using a mock library like https://www.npmjs.com/package/aws-sdk-mock

**Comment by pgherveou** [comment]
Great ideas.
Travis should be activated now
Mocking aws for tests seems like a good idea, unless you find an easy way to safely configure it with yours in travis

**Comment by pioug** [comment]
Nice! Thank you @pgherveou. CI is up! https://www.travis-ci.org/pgherveou/gulp-awspublish/builds/435916207. I created a PR https://github.com/pgherveou/gulp-awspublish/pull/164.

**Comment by pioug** [comment]
I updated some dependencies and released `v3.4.1-rc` (https://www.npmjs.com/package/gulp-awspublish/v/3.4.1-rc.0). It's a pre-release, just in case 😅 But the CI is cool! I feel way more confident pushing things now.
