### ISSUE TITLE
AccessDenied - Non-Public S3 Breaks gulp-awspublish

### ISSUE THREAD

**Issue by arlogilbert** [pgherveou/gulp-awspublish#165]
Long time user of this plugin and we keep forgetting one rule that is not documented.

No matter what your IAM privileges are (you can have full root access keys if you want).... If your S3 Bucket is set to prevent public ACLS you will spend 6 hours pulling your hair out over why you get an Access Denied message.

This is what it NEEDS to look like.

![Screen Shot 2019-04-19 at 10 11 38 PM](https://user-images.githubusercontent.com/6061697/56451194-31e0cd00-62f0-11e9-9d02-7712ca96141a.png)

**Comment by pioug** [comment]
Thank you for reporting this. I added a section in the readme. Feel free to reword if it's incorrect 🙏
