### ISSUE TITLE
Sync does not allow the deletion of more than 1000 keys/files

### ISSUE THREAD

**Issue by rmoskal** [pgherveou/gulp-awspublish#176]
This was introduced in breaking the 1K file retrieval limit in the latest release (by me :)).  The deleteObjects S3 call has a 1K file limit, so the request needs to broken up into 1K chunks.

**Comment by Twipped** [comment]
Something else weird is happening too. I just downgraded back to 4.0.1 because the push kept crashing when trying to delete just two files.

**Comment by rmoskal** [comment]
Yes, there is something else very strange happening.  Sync  works when I run it locally (via npm link or by simply pointing to a relative path on my file system in package.json), but as soon as I use a remote version it does not.  It's the darndest thing.  I am investigating.

**Comment by pioug** [comment]
PR squash-merged https://github.com/pgherveou/gulp-awspublish/commit/59490e860518bc3732526b38160fc7977435710d. Fixed in `v4.1.1` (https://github.com/pgherveou/gulp-awspublish/releases/tag/v4.1.1).
