### ISSUE TITLE
Why does it require "public" access to a bucket?

### ISSUE THREAD

**Issue by slavafomin** [pgherveou/gulp-awspublish#178]
Hello!

Thank you for this nice tool!

However, why exactly does it require "public" access to a bucket?

I'm serving my content using CloudFront and I want to configure my bucket to be private (I don't want content to be directly accessible). This is considered a best practice in AWS.

**Comment by pioug** [comment]
I did a quick test and it should work with private buckets (_Block all public access: On_) by passing `{ noAcl: true }` or a value for the `'x-amz-acl'` header:

```js
publisher.publish({}, { noAcl: true });
publisher.publish({ 'x-amz-acl': 'something' });
```

If it still not working for you, please share your bucket permission so I can investigate.

I wrote this part https://github.com/pgherveou/gulp-awspublish#bucket-permissions and now I realise that it's misleading 🙈🙈🙈 The thing is by default, `publisher.publish()` works only for public bucket. I will reword that part, or you can create a PR if you want 🙏

**Comment by slavafomin** [comment]
@pioug thank you for a quick reply and a suggestion. `noAcl: true` actually helped to resolve the issue in my case.
