### ISSUE TITLE
through2 still used in lib/log-reporter.js, but removed from package.json

### ISSUE THREAD

**Issue by TruffeCendree** [pgherveou/gulp-awspublish#205]
Thanks for managing this package.

We are unable to switch to v6.0.1 because the `through2` dependency was removed from `package.json`, but is still used in `lib/log-reporter.js`.

**Comment by pioug** [comment]
@TruffeCendree Hello, thanks for reporting this ! Can you test the PR https://github.com/pgherveou/gulp-awspublish/pull/206 ? I've never used the reporter and it's not covered with tests 💦

**Comment by TruffeCendree** [comment]
I will test it tomorrow.

**Comment by TruffeCendree** [comment]
I was able to deploy by using your PR. Thanks.

**Comment by pioug** [comment]
https://github.com/pgherveou/gulp-awspublish/releases/tag/v6.0.2
