### ISSUE TITLE
Automatically update Index Document and Error Document values

### ISSUE THREAD

**Issue by koistya** [pgherveou/gulp-awspublish#21]
Is there a way to automatically update `Index Document` and `Error Document` values in S3 bucket settings after deployment?

**Comment by jstejada** [comment]
@pgherveou I have the same use case. Indeed there is an endpoint to update the `Index Document`, but how can I get the generated file names from rev-all?

**Comment by pgherveou** [comment]
Not familiar with this plugin but it seems that you can access the original filename (https://github.com/smysnk/gulp-rev-all#filerevpathoriginal) and thus add a condition to run your custom aws code
