### ISSUE TITLE
Unsure how to upload to specific folder

### ISSUE THREAD

**Issue by AshCoolman** [pgherveou/gulp-awspublish#29]
From reading the documentation I've only been able to upload to the root directory. I'm a bit nervous about experimenting with the particular aws server I'm publishing to. Could you perhaps include an example in the docs of uploading to a specific folder? thanks

EDIT:  I must be blind:

// see examples/rename.js

gulp.src('examples/fixtures/*.js')
    .pipe(rename(function (path) {
        path.dirname += '/s3-examples';
        path.basename += '-s3';
    }))
    .pipe(publisher.publish())
    .pipe(awspublish.reporter());

// output
// [gulp] [create] s3-examples/bar-s3.js
// [gulp] [create] s3-examples/foo-s3.js

**Comment by Prinzhorn** [comment]
Is this still the same? Or maybe I'm too tired. Here's what I do:

```js
gulp.src(['./dist/bundle.js', './dist/style.css'])
	.pipe(awspublish.gzip())
	.pipe(rename(function(path) {
		path.dirname = 'public/assets/' + path.dirname;
	}))
	.pipe(publisher.publish(headers))
	.pipe(awspublish.reporter());
});
```

```
[15:12:01] [create] bundle.js
[15:12:01] [create] style.css
```

both files are now in the bucket root. No matter what I've tried, they always end up in the root.

**Comment by pgherveou** [comment]
this plugin use the relative path of your vinyl file 
try to tweak the base maybe
```js
gulp.src(['./dist/bundle.js', './dist/style.css'], {  base: './dist' })
```

**Comment by Prinzhorn** [comment]
@pgherveou I found the issue/bug #82
