### ISSUE TITLE
[doc] add region to awspublish parameters

### ISSUE THREAD

**Issue by jmbarbier** [pgherveou/gulp-awspublish#35]
Just as a reminder that could be in the docs : if you use a non-us bucket (eu-west-1 for example), you have to add the region parameter to awspublish.create

It's a common mistake, but as there are no errors on failures, it can be hard to diagnose.

**Comment by pgherveou** [comment]
Thks for the feedbacks
the doc already point to https://github.com/LearnBoost/knox#client-creation-options but if you you can add a more meaningful example if you wish and I will merge your pull request
