### ISSUE TITLE
proposal: use semver

### ISSUE THREAD

**Issue by klaemo** [pgherveou/gulp-awspublish#39]
Hey,
would you consider adopting the semantic versioning scheme?

Thanks

**Comment by pgherveou** [comment]
Sure I can be more strict about it!

**Comment by klaemo** [comment]
I think starting with 1.0.0 once the aws-sdk PR is merged would be a good idea. :)



> Am 29.01.2015 um 18:12 schrieb PG Herveou <notifications@github.com>:
> 
> Sure I can be more strict about it! 
> 
> 
> Sent from my iPhone 
> 
>

**Comment by pgherveou** [comment]
Good idea :)
all done
