### ISSUE TITLE
Format of bucket name?

### ISSUE THREAD

**Issue by hlassiege** [pgherveou/gulp-awspublish#41]
Hi,

I'm new to AWS and I tried to use gulp-awspublish to upload somes files on a s3 bucket.
Hower, I always get and error : 

C:\***\node_modules\gulp-awspublish\node_modules\aws-sdk\lib\request.js:32
          throw err;
                ^
NoSuchBucket: The specified bucket does not exist

```
    var publisher = awspublish.create({
        key: '...',
        secret: '...',
        bucket: 'arn:aws:s3:::mybucket'
    });
```

I've tried with 
mybucket (=> BadRequest: null)
arn:aws:s3:::mybucket (=> NoSuchBucket: The specified bucket does not exist)
mybucket.s3-website.eu-central-1.amazonaws.com (=> NoSuchBucket: The specified bucket does not exist)

Any idea ?

**Comment by pgherveou** [comment]
it should work with bucket: 'myBucket'
Have a look here http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html
Make sure your can connect using make aws-sdk module. If it works it should work with  gulp-awspublish too.

**Comment by hlassiege** [comment]
Ok, I found it. It is necessary to give the 'region' param

var publisher = awspublish.create({
        region : 'eu-central-1',
        key: '***',
        secret: '***',
        bucket: 'mybucket'
    });

I guess it thanks to this file https://github.com/aws/aws-sdk-js/blob/master/configuration.sample

Thanks,
Bye

**Comment by pgherveou** [comment]
Cool, 
dont hesitate to add a note on the readme and send a PR, if you think things could be clearer!
