### ISSUE TITLE
Usage of the prefix in sync()

### ISSUE THREAD

**Issue by adrienkohlbecker** [pgherveou/gulp-awspublish#44]
Hello,

I wanted to scope the sync to a subdirectory of my bucket. For this I set the prefix like this :
```
gulp.src(DIST_DIR+'/**')
        .pipe(publisher.publish())
        .pipe(publisher.sync('v2'))
        .pipe(awspublish.reporter());
```

But the files are synced to the root of the bucket. Is this a bug or a misunderstanding on my part ?

Thanks

**Comment by adrienkohlbecker** [comment]
So I figured it out, you have to use both the prefix in sync and gulp-rename.
Could be clarified in the readme?

**Comment by pgherveou** [comment]
can u send me a sample of the code you are using so I can understand it better?

**Comment by adrienkohlbecker** [comment]
Here you go:

```
    var publisher = awspublish.create(config.aws);

    gulp.src(config.DIST_DIR+'/**')
      .pipe(rename(function (path) {
          path.dirname = config.aws.subdirectory + "/" + path.dirname;
      }))
      .pipe(publisher.publish())
      .pipe(publisher.sync(config.aws.subdirectory))
      .pipe(publisher.cache())
      .pipe(awspublish.reporter())
      .on('end', function() {
        // Here because gulp-cloudfront needs to set the root object without the subdirectory
        gulp.src(global.config.DIST_DIR+'/**')
          .pipe(cloudfront(config.aws))
          .on('end', cb);
      });
```

What I gathered from the source code is:
- gulp-rename is used for uploading the files in the directory
- the argument to `sync` is used to scope the deletion of the old files (otherwise the other directories get deleted)

**Comment by pgherveou** [comment]
You are doing it right, but that seems to be specific to your directory structure,
(not everybody use remame first)
Feel free to send me a PR to add more precision to the docs or to add more examples inside the examples folder

**Comment by jhg-tgu** [comment]
Same error, if I rename and use prefix the old files are not deleted
