### ISSUE TITLE
[question] Shared cache file

### ISSUE THREAD

**Issue by bogdan-dumitru** [pgherveou/gulp-awspublish#48]
I'm trying to wrap my head around how to use the cache on a project with multiple devs. Basically the question is, do you suggest keeping the cache file(s) in the repo so that everybody has the same cache file when running a deploy, or is there some other way of keeping things in sync?

Everybody having their own version of the cache file is bad, because it may cause some assets to not update when they should, while keeping it in the repo will add the need to create an extra commit after each deploy-build with the new asset cache.

Can we somehow keep the cache file in S3 as well and load it from there / write it there, or am I way off?

Thanks!

**Comment by pgherveou** [comment]
You could add the deployment to s3 after a post-receive action on a bare repository from your build server. 

I won't worry to much about the cache, the plugin make a head request to check that the files are different before uploading anything

**Comment by bogdan-dumitru** [comment]
Got it cool, thanks for the info!
