### ISSUE TITLE
Crash when using sync()

### ISSUE THREAD

**Issue by argelius** [pgherveou/gulp-awspublish#51]
Hi,

When I use sync it crashes when it tries to delete a file. Upload works fine:

My task:

```
var headers = {'Cache-Control': 'max-age=900, no-transform, public'};

var stream = merge(site, templates, build)
  .pipe(awspublish.gzip())
  .pipe(publisher.publish(headers))
  .pipe(publisher.sync())
  .pipe(awspublish.reporter());
```

The stack trace is quit long so i pasted it on pastebin:
http://pastebin.com/SKHKpzXV

This is in version 1.0.3. I just saw that you tagged 1.0.4, so I'll try that shortly.

**Comment by pgherveou** [comment]
first line of the stack seems to be related to an other module gulp-cloudfront
Can you have a look at whats going here?

```
TypeError: Cannot call method 'substr' of undefined
  at Transform._transform (/Users/bla/node_modules/gulp-cloudfront/index.js:21:34)
```

if you are piping stuff (other than the reporter) after the sync method that might cause some issues cause we are adding fake deleted files into the stream

**Comment by pgherveou** [comment]
just pushed a fix, try out 1.0.5 and let me know if things works for you

**Comment by argelius** [comment]
Thanks @pgherveou !

I tried deploying again at it worked like a charm. Now I can use `sync()` again. :)

**Comment by ianks** [comment]
This is still failing for me. Not sure why.

**Comment by pgherveou** [comment]
Any stack trace?
The sync method is adding
Some blank files into the stream so we can pipe all the deleted file in the reporter, so if you pipe anything after it,make sure to test the file content or the s3.state file

**Comment by ianks** [comment]
Pipe deleted files? Why not just have a boolean to indicate whether the file had been deleted and use on sync those objects? Seems bad to make it so the user has to worry about that logic.

Here's my gulp task that fails:

```js
gulp.task('publish', function() {
  var aws = {
    "key": process.env.AWS_ACCESS_KEY,
    "secret": process.env.AWS_SECRET_KEY,
    "bucket": "hackcu",
    "distributionId": "E2EHAFBXJFNUF"
  };

  var headers = {"x-amz-acl" : "public-read"}

  var publisher = awspublish.create(aws);

  return gulp.src('dist/**/*')
    .pipe(revall())
    .pipe(awspublish.gzip())
    .pipe(parallel(publisher.publish(headers), os.cpus().length))
    .pipe(publisher.cache())
    .pipe(publisher.sync())
    .pipe(awspublish.reporter())
    .pipe(cloudfront(aws));
});
```

**Comment by pgherveou** [comment]
Because you might want to list these files in the reporter or use these references to remove these files from another cache... It should be easy to build a stream that filter these files out 
You could move the sync at the end of your pipe chain otherwise
