### ISSUE TITLE
documentation of v2.0.0 config

### ISSUE THREAD

**Issue by danielberndt** [pgherveou/gulp-awspublish#60]
I just tried updating my configuration to the v2.0.0 style. I didn't get very far however. I already learned that I need to use S3-SDK style params. But I couldn't find how to do what I did before. 

This is my old code:
```
var publisher = awspublish.create({bucket: "my.bucket.name", profile: "my-profile", region: "eu-central-1"});
```

I know that the bucket now needs to be passed as `{params: {Bucket: "my.bucket.name"}}`. But how about the rest? Any pointer to the correct docs would be greatly appreciated. And I guess that an overview of the most common configs in the README would help a lot of other people as well.

Cheers,
Daniel

**Comment by benc** [comment]
I got it working using

    var publisher = awspublish.create({bucket: "my.bucket.name"}, profile: "my-profile", region: "eu-central-1");

**Comment by danielberndt** [comment]
Thanks! But is this valid javascript? it seems `profile` and `region` aren't part of any object literal.

**Comment by benc** [comment]
Woops, you're right.

    var publisher = awspublish.create({{bucket: "my.bucket.name"}, profile: "my-profile", region: "eu-central-1"});

Working example [here](https://github.com/benc/www.cochezconsult.be/blob/master/tasks/publish.js)

**Comment by pgherveou** [comment]
The doc already specify the link to setup your aws options http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property
but if it is still unclear please feel free to reopen this issue and eventually push a PR to fix the doc

**Comment by danielberndt** [comment]
I just got around actually updating to 2.0 and for reference's sake here's the code to enable working with [profiles](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Using_Profiles_with_the_SDK) for credentials:
```
var publisher = awspublish.create({
  params: {Bucket: "my.bucket.com"},
  region: "eu-central-1",
  credentials: new AWS.SharedIniFileCredentials({profile: "my-profile"})
});
```

**Comment by pgherveou** [comment]
Cool, dont hesitate to  add a note in the readme
