### ISSUE TITLE
Breaking API change in 1.0.7 - really?

### ISSUE THREAD

**Issue by bradvogel** [pgherveou/gulp-awspublish#62]
Why did you merge https://github.com/pgherveou/gulp-awspublish/commit/f7efee88f6749d8c20be2674f0aa4368b2305d08 into 1.0.7? It broke our entire deployment. Please bump the major version when making a major API change!

**Comment by wearhere** [comment]
+1

**Comment by alexgorbatchev** [comment]
Somebody didn't merge package.json correctly, I will fix.

**Comment by alexgorbatchev** [comment]
I have published `1.0.9` to fix the issue for you and unpublished `1.0.6` and `1.0.7`. Sorry about that.

**Comment by bradvogel** [comment]
Still at https://www.npmjs.com/package/gulp-awspublish. Can you please publish?

**Comment by alexgorbatchev** [comment]
Sorry, keep forgetting about internal registry... I can't seem to unpublish `1.0.8` from publish registry even though it reports success. There's `1.0.9` and `2.0.2` now published.
