### ISSUE TITLE
Problems with file naming

### ISSUE THREAD

**Issue by hrajchert** [pgherveou/gulp-awspublish#63]
Hi, I have two problems using the library.

I have a file structure like this

```
public/
  js/
    /runner
      file1.js
      file2.js
```
And using this code 

```js
gulp.src('public/js/runner/*.js', {base: 'public'})
		.pipe(publisher.publish(headers, {simulate:true}))
		.pipe(awspublish.reporter());
```

It resolves the file.s3.path to `/hrajchert/project/public/js/runner/file1.js`, which would be the absolute path to the file (clearly not what I want as s3 key)

If I add an empty gulp-rename like this

```js
gulp.src('public/js/runner/*.js', {base: 'public'})
		.pipe(rename(function (path) {
			// This is weird, but is needed to make the file use the relative path...
		}))
		.pipe(publisher.publish(headers, {simulate:true}))
		.pipe(awspublish.reporter());
```

Now the path is `/js/runner/file1.js` which is almost what I wanted, but the initial `/` causes a problem in S3, in the sense that it creates an initial empty folder so my resource has to have two // like this `myawsdomain//js/runner/file1.js`

So the final solution is to have a trailing slash in my base

```js

gulp.src('public/js/runner/*.js', {base: 'public/'})
		.pipe(rename(function (path) {
			// This is weird, but is needed to make the file use the relative path...
		}))
		.pipe(publisher.publish(headers, {simulate:true}))
		.pipe(awspublish.reporter());		
```

So there are basically two problems... I require to use gulp-rename to avoid using absolute path (dont know why), and you probably should add a check to never start a path with initial /, I doubt that would be useful in any case.

Thanks!

**Comment by pgherveou** [comment]
I am not sure your errors are specific to this plugin
This plugin just use the file.path that it receive from the gulp stream, 
you should tweak your gulp.src call and maybe use something like https://www.npmjs.com/package/gulp-debug to debug whats coming into the stream

Closing this issue now but feel free to reopen it if it still unclear

**Comment by rossthedevigner** [comment]
@hrajchert did you get this figured out? I just ran into the same issue with a prefixed `/` before my bucketPath.

**Comment by hrajchert** [comment]
Well, the last snippet that I had it's what worked for me and it's what I currently have in my gulpfile, but seems quite like a hack.

@pgherveou its not exactly an error but a feature missing I think. The initial / is doubtfull to be included in any s3 key, because of the behaviour I commented. The relative path part could be discussed

**Comment by merqurio** [comment]
I'm having the same issue too only when deploying through travis-ci though. I'll try renaming the paths...
