### ISSUE TITLE
Doc issue: sync and publish

### ISSUE THREAD

**Issue by JamesMcMahon** [pgherveou/gulp-awspublish#64]
What's the difference between the `publish` and `sync` API? It's unclear looking at the README.

**Comment by pgherveou** [comment]
Sync create a stream that can be piped after publish to remove files that are not in your local directory (or input stream) anymore. 

Does it make more sense? Please feel free to update the doc and send a PR to make it clearer

**Comment by JamesMcMahon** [comment]
Let me make sure I understand correctly, publish will never delete files remotely?

**Comment by pgherveou** [comment]
Yes It can update files but wont do any delete

**Comment by pgherveou** [comment]
You are right about  running sync after publish, 
Only use sync if you want to keep your local folder in sync with s3, in every scenarios where you just need to add files then its not necessary. Let me know if this is still not clear and agian feel free clarify the doc and close this issue when you are done!

**Comment by JamesMcMahon** [comment]
Thanks for the clarification. I created a PR to help improve the docs.
