### ISSUE TITLE
Question: Is it possible to upload both gzipped and non-gzipped files?

### ISSUE THREAD

**Issue by JamesMcMahon** [pgherveou/gulp-awspublish#65]
It is possible to upload both gzipped and non-gzipped files in a single task?

Currently I have the following:
```js
var gulp = require("gulp");
var awspublish = require('gulp-awspublish');
var rename = require("gulp-rename");

var publisher = awspublish.create({
    params: {
        Bucket: 'test-bucket'
    }
});

function prefixFile(path) {
    path.dirname = '/foo/' + path.dirname;
}

gulp.task('s3:gzip', function() {
    return gulp.src('public/**/*')
        .pipe(rename(prefixFile))
        .pipe(awspublish.gzip({ ext: '.gz' }))
        .pipe(publisher.cache())
        .pipe(publisher.publish())
        .pipe(awspublish.reporter());
});

gulp.task('s3:plain', function() {
    return gulp.src('public/**/*')
        .pipe(rename(prefixFile))
        .pipe(publisher.cache())
        .pipe(publisher.publish())
        .pipe(awspublish.reporter()); 
});

```

But if I try to add `sync` to either or these tasks they delete each other's files. Is it possible to do this is in single task so that `sync` respects that both versions of the file should be uploaded?

**Comment by pgherveou** [comment]
You should be able to create two streams merge them and then sync

**Comment by JamesMcMahon** [comment]
Ah, thanks for the tip, this is what I ended up doing:

```js
var gulp = require("gulp");
var awspublish = require('gulp-awspublish');
var rename = require("gulp-rename");
var merge = require('merge-stream');

var publisher = awspublish.create({
    params: {
        Bucket: 'test-bucket'
    }
});

function prefixFile(path) {
    path.dirname = '/foo/' + path.dirname;
}

gulp.task('s3', function() {
    var gzipFilter = [
        'public/**/*.js', 'public/**/*.html',
        'public/**/*.css', 'public/**/*.xml',
        'public/**/*.txt', 'public/**/*.ico',
        'public/**/*.json',
    ];
    var negativeFilter = gzipFilter.map(function(x) {
        return '!' + x;
    });

    var gzip = gulp.src(gzipFilter)
        .pipe(rename(prefixFile))
        .pipe(awspublish.gzip());

    var plain = gulp.src(['public/**/*'].concat(negativeFilter))
        .pipe(rename(prefixFile));

    return merge(gzip, plain)
        .pipe(publisher.cache())
        .pipe(publisher.publish())
        .pipe(publisher.sync())
        .pipe(awspublish.reporter());
});
```

Think something like this is worth adding to the examples? I can create a PR when I get a chance.

**Comment by pgherveou** [comment]
yep but maybe just specify the part not specific to your app so just keep

    var gzip = gulp.src(zipfiles)
        .pipe(awspublish.gzip());

    var plain = gulp.src(plainFiles)

    return merge(gzip, plain)
        .pipe(publisher.cache())
        .pipe(publisher.publish())
        .pipe(publisher.sync())
        .pipe(awspublish.reporter());


On Thu, Jun 4, 2015 at 11:52 AM, James F McMahon <notifications@github.com>
wrote:

> Ah, thanks for the tip, this is what I ended up doing:
>
> var gulp = require("gulp");var awspublish = require('gulp-awspublish');var rename = require("gulp-rename");var merge = require('merge-stream');
> var publisher = awspublish.create({
>     params: {
>         Bucket: 'test-bucket'
>     }
> });
> function prefixFile(path) {
>     path.dirname = '/foo/' + path.dirname;
> }
>
> gulp.task('s3', function() {
>     var gzipFilter = [
>         'public/**/*.js', 'public/**/*.html',
>         'public/**/*.css', 'public/**/*.xml',
>         'public/**/*.txt', 'public/**/*.ico',
>         'public/**/*.json',
>     ];
>     var negativeFilter = gzipFilter.map(function(x) {
>         return '!' + x;
>     });
>
>     var gzip = gulp.src(gzipFilter)
>         .pipe(rename(prefixFile))
>         .pipe(awspublish.gzip());
>
>     var plain = gulp.src(['public/**/*'].concat(negativeFilter))
>         .pipe(rename(prefixFile));
>
>     return merge(gzip, plain)
>         .pipe(publisher.cache())
>         .pipe(publisher.publish())
>         .pipe(publisher.sync())
>         .pipe(awspublish.reporter());
> });
>
> Think something like this is worth adding to the examples? I can create a
> PR when I get a chance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pgherveou/gulp-awspublish/issues/65#issuecomment-109007668>
> .
>



-- 
--
PG
