### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by ramonck** [pgherveou/gulp-awspublish#69]
I think you guys just have to work a bit on the documentation but the product is great, works great in my project.

It would be nice to have the newest feature of storing the zip file in an S3 bucket instead of local hosting and upload.

Best Regards,

**Comment by pgherveou** [comment]
Thks @ramonck!
Dont hesitate to submit a PR with your changes to the documentation if you think of way to make it better.

As for the  feature you are talking about, I am not sure to understand exactly what you are asking for

**Comment by ramonck** [comment]
The feature is related to this new item https://forums.aws.amazon.com/ann.jspa?annID=3072

Best Regards

**Comment by akrisanov** [comment]
I agree that the uploading of build zip archive would be very useful feature.
One of the use cases is a deploy an application with Amazon OpsWorks from S3 bucket.

![edit_site-staging_-_apps_-_core_staging__aws_opsworks_2016-04-13_21-30-57](https://cloud.githubusercontent.com/assets/238505/14505000/484e7272-01c8-11e6-9308-e4263b0933d4.png)

**Comment by akrisanov** [comment]
@ramonck You also can do this in your gulpfile:

```
gulp.task('zip', function() {
    return gulp.src('./build/**')
        .pipe(zip('release_' + process.env.NODE_ENV + '.zip'))
        .pipe(gulp.dest('./releases'));
});

gulp.task('awspublish', ['build', 'zip'], function() {
    var config = require('./aws-credentials.json')
    var envs   = config[process.env.NODE_ENV]

    if(envs == undefined) {
      throw new Error("Please provide aws credentials.");
    }

    var publisher = awspublish.create(envs);
    var plain     = gulp.src(['./releases/' + 'release_' +
                              process.env.NODE_ENV + '.zip'])

    return merge(plain).pipe(publisher.publish())
                       .pipe(publisher.sync())
                       .pipe(publisher.cache())
                       .pipe(awspublish.reporter());
});
```
