### ISSUE TITLE
Output log file of file.s3.state

### ISSUE THREAD

**Issue by rossthedevigner** [pgherveou/gulp-awspublish#70]
One of the great features is seeing what files are created, skipped, updated, etc. For logging reasons, would it be of interest to write out the changed or updated cache items to a log file or to service hook like slack.

**Comment by pgherveou** [comment]
all this infos are attached to the vinyl file, the only thing you need to do is plug an other transform stream to send this out to wherever you wish to.
the log-reporter https://github.com/pgherveou/gulp-awspublish/blob/master/lib/log-reporter.js is just printing that out in the console but feel free to create your own module to send that to Slack if this is what you want to do

**Comment by pgherveou** [comment]
closing for now let me know if this is not clear
