### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by jasonhenderson** [pgherveou/gulp-awspublish#71]
Thanks for putting this together.

I am new to automated s3 publishing, so please forgive my ignorance. I am getting Access Denied from the aws-sdk and it is probably due to my policy configuration.

Here is my config in the gulpfile (hard-coded for testing only, will transition to aws credentials suggested scheme once i get it working):

```
var awsConfig = {
    params: {
        "Bucket": "bucket-1"
    },
    "accessKeyId": "...",
    "secretAccessKey": "...",
    "region": "", // needed for us-standard, failing if us-standard is used in the region
};

On AWS, I have an IAM policy for a group, and a user with the credentials provided in the awsConfig assigned to that group. Here is that policy: 

{
    "Version": "2015-6-8",
    "Statement": [
        {
            "Sid": "Stmt1396513442000",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject",
                "s3:ListMultipartUploadParts",
                "s3:AbortMultipartUpload",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-1/*",
                "arn:aws:s3:::bucket-1",
                "arn:aws:s3:::bucket-2/*",
                "arn:aws:s3:::bucket-2"
            ]
        }
    ]
}
```
Am I missing something?

**Comment by jasonhenderson** [comment]
From what I could tell while going through the AWS-SDK logs, this is likely an issue with IAM policies. For now, I set the Action to "*" for the bucket and its objects, and it pushes the files up there. If I ever get around to isolating which actions are actually required, I will report back.

**Comment by kremalicious** [comment]
Just confirming the listed actions in the ReadMe are not enough. Created an IAM user and attached this policy to give access to a specific bucket:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKET"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:ListMultipartUploadParts",
                "s3:AbortMultipartUpload"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKET/*"
            ]
        }
    ]
}
```

With this policy, gulp-awspublish just error out with `AccessDenied: Access Denied`. When adding the action `s3:*` everything works. Would be splendid to know which additional actions are needed.

**Comment by alexgorbatchev** [comment]
Is `s3:*` action alone enough then? I'm pretty sure another more specific action might do the trick.

**Comment by kremalicious** [comment]
yes, `s3:*` alone for the bucket contents works.

**Comment by pizthewiz** [comment]
Thanks for the issue and workaround, I hit the same thing trying to limit an IAM user to a single bucket and this got things sorted.

**Comment by juanqui** [comment]
It appears this library also needs the following permissions on the IAM user:
* `s3:GetObjectAcl`
* `s3:PutObjectAcl`

**Comment by ianbytchek** [comment]
@juanqui thanks! That did the trick.

**Comment by jakerobers** [comment]
For future devs having a similar error: I forgot to add my newly created user to the group.

**Comment by nathanredblur** [comment]
Thanks for this.
This is how look the IAM:Policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAME"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:DeleteObject",
                "s3:ListMultipartUploadParts",
                "s3:AbortMultipartUpload"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        }
    ]
}
```

This was more useful for solve my problem that README file. 
Thanks again.

**Comment by pgherveou** [comment]
Thanks for the issue and workaround
@nathanredblur can you push your updates to the readme if you think it can help others ?

**Comment by nathanredblur** [comment]
Sure I can :)

**Comment by MichaelJCole** [comment]
AWS config above has changed w/o updating the documentation.  See this PR if you're getting access denied:  https://github.com/pgherveou/gulp-awspublish/pull/135/commits/c5ab23d9223378163df2fac11892d90ad063f6a3
