### ISSUE TITLE
Not Deploying on West-2 since this morning

### ISSUE THREAD

**Issue by ramonck** [pgherveou/gulp-awspublish#72]
Hey guys,
Some change happened since this morning I'm not able to deploy through this tool, I've to upload manually and that's with any function on west-2.
Thanks for your time.
Best Regards,

**Comment by pgherveou** [comment]
Can you still connect manually with the awk sdk?

On Thu, Jun 18, 2015 at 8:01 PM, ramonck <notifications@github.com> wrote:

> Hey guys,
> Some change happened since this morning I'm not able to deploy through
> this tool, I've to upload manually and that's with any function on west-2.
> Thanks for your time.
> Best Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pgherveou/gulp-awspublish/issues/72>.
>



-- 
--
PG

**Comment by ramonck** [comment]
Hello,

Not sure how I can connect manually with the AWS SDK, can you tell me?

I was able to connect into the Console and upload my function manually, that's working fine. But I really love the fact that I was always calling up the gulp command and it was working like a charm, I really like this gulp plugin and I want to keep on using it, please fix it :).

Best Regards,

**Comment by JamesMcMahon** [comment]
>Some change happened since this morning I'm not able to deploy through this tool

The project hasn't had a release since May so unless you just updated from an older version I think it's very likely that the problem is with your AWS configuration. 

What error are you seeing?

**Comment by ramonck** [comment]
no updates in gulp and no changes in my AWS Configuration and I don't see any erros :(.

**Comment by ramonck** [comment]
Are you guys able to upload to west-2? Not sure why it stopped working, can I get log somewhere?

Tried it again and nothing, had to do manual upload again.

Best Regards,

**Comment by ramonck** [comment]
It's working now :), didn't change anything, someone woke up and turned the switch back on :).

Thanks guys!
