### ISSUE TITLE
Can't use absolute path in sync

### ISSUE THREAD

**Issue by ianbytchek** [pgherveou/gulp-awspublish#75]
Oh gosh… I hope I didn't develop a wrong habit, but I tend to use full absolute paths for bucket keys, e.g., `/foo/bar/baz.qux`. Frankly, in the following the sync part doesn't work.

```js
gulp.src('../../qux/*')
    .pipe(rename(function (path) {
        path.dirname = '/foo/bar';
    }))
    .pipe(publisher.publish(null, {force: true}))
    .pipe(publisher.sync('/foo'))
    .pipe(awspublish.reporter());
```

But if I change `publisher.sync('/foo')` to `publisher.sync('foo')` everything works as expected. I use `s3ForcePathStyle` in my config, which might be related? What do you think?

**Comment by pgherveou** [comment]
I dont really remember but have a look at the source 
and add some console.log around these lines to see which path slyle we used 
https://github.com/pgherveou/gulp-awspublish/blob/master/lib/index.js#L391

**Comment by pgherveou** [comment]
fixed by https://github.com/pgherveou/gulp-awspublish/pull/81
