### ISSUE TITLE
Everything gets published inside an empty-named directory

### ISSUE THREAD

**Issue by ianbytchek** [pgherveou/gulp-awspublish#80]
:worried: 

Basically. This.

![image](https://cloud.githubusercontent.com/assets/1086845/9289986/efba3724-4389-11e5-9a18-d26c0c04164c.png)

For some reason, it creates a directory / key, with an empty name, and puts everything in there. I'd expect S3 not to allow this, frankly. This is eu-central-1, which is known for awkward situations. I haven't tested in other regions, but assuming it's ok. I use aws-publish with local Riak-CS instance, which is AWS-compatible storage. No problems there. Other libraries work as expected in eu-central-1.

```js
pipeline = pipeline
    .pipe(rename(function (path) {
        path.dirname = '/' + appConfiguration['release'] + '/' + path.dirname;
    }))
    .pipe(publisher.publish(null, {force: true}))
    .pipe(awspublish.reporter());
```

Tried removing the first backslash and tried setting the dirname to an empty string. No go. What do you think?

**Comment by ianbytchek** [comment]
Happens [here](https://github.com/pgherveou/gulp-awspublish/blob/e0a713a3eadc2c0a2986dfae37d5172453ad5f67/lib/index.js#L87) because of this:

```js
file.path.substring(file.base.length).replace(/\\/g, '/');
```

When src base parameter to gulp is specified without trailing slash, the resulting aws key will always start with the slash. E.g., path is `/foo/bar/baz/qux.json` and base is `/foo/bar`, the key will be `/baz/qux.json`. I'm used to "absolute" notation where keys start with slash, apparently that's not the way it should be used and probably other libraries get rid of it automatically.

**Comment by pgherveou** [comment]
should be fixed in the last release after merging 
https://github.com/pgherveou/gulp-awspublish/pull/81

**Comment by kremalicious** [comment]
This is happening again on my side. Seems to have started going wrong about 2 weeks ago. Also using eu-central-1

**Comment by jhulst** [comment]
@kremalicious I'm seeing this again too, were you able to resolve?

**Comment by kremalicious** [comment]
@jhulst no, still having the same problem
