### ISSUE TITLE
Doesn't pick up /build directory if it was just created from build task

### ISSUE THREAD

**Issue by jarodtaylor** [pgherveou/gulp-awspublish#83]
Okay, so I'm using metalsmith to just generate a simple build directory with static assets in it (index.html, main.css, etc). If the /build directory doesn't exist first (say it was deleted by gulp-clean, or w/e) but is created prior to running the awspublish task:

`gulpfile.js` has this in it:
```
var gulp = require('gulp');

gulp.task('metalsmith', require('./tasks/metalsmith'));
gulp.task('styles', require('./tasks/styles'));

gulp.task('deploy', ['metalsmith', 'styles'], require('./tasks/deploy'));

```
So prior to my deploy task I'm running `metalsmith` and `styles` which do their thing and create a `/build` directory with an index.html and main.css file in it. 

Let's say I've deleted the `/build` directory (manually with `rm -rf`, or using `gulp-clean`) prior to the metalsmith and styles tasks (which generate a new /build directory with static files in it). This is what I'll see:
```
 $ gulp deploy
[12:34:21] Using gulpfile ~/Sites/jarodtaylor_metalsmith/gulpfile.js
[12:34:21] Starting 'metalsmith'...
[12:34:21] Finished 'metalsmith' after 99 ms
[12:34:21] Starting 'styles'...
[12:34:21] Finished 'styles' after 5.96 ms
[12:34:21] Starting 'deploy'...
[12:34:21] Finished 'deploy' after 24 ms
```
The deploy task runs, but nothing is uploaded to S3. Now, if I don't delete the `/build` directory, and just run `gulp deploy` again:

```
 $ gulp deploy
[12:37:11] Using gulpfile ~/Sites/jarodtaylor_metalsmith/gulpfile.js
[12:37:11] Starting 'metalsmith'...
[12:37:11] Finished 'metalsmith' after 109 ms
[12:37:11] Starting 'styles'...
[12:37:11] Finished 'styles' after 6.77 ms
[12:37:11] Starting 'deploy'...
[12:37:12] [create] index.html
[12:37:13] [create] main.css
[12:37:14] [create] main.css.map
[12:37:15] [create] about/index.html
[12:37:15] Finished 'deploy' after 4.39 s

```

This works because the build directory was there before I ran the gulp deploy task. But if I made changes to files in metalsmith or styles, it won't pick them up. It picks up what's currently in the build directory. Making the `['metalsmith', 'styles']`tasks before `deploy` useless.

I'm assuming this isn't necessarily gulp-awspublish fault. I'm just hoping someone can shed some light on how to get this to work.

BTW, this is my `./tasks/deploys.js` file:

```
var gulp = require('gulp'),
    awspublish = require('gulp-awspublish');

module.exports = function() {
  var publisher = awspublish.create({
    params: {
      Bucket: 'jarodtaylor'
    }
  });

  var headers = {
   'Cache-Control': 'max-age=0,public'
  };

  return gulp.src('./build/**/*')
        // .pipe(awspublish.gzip({ext: '.gz'}))
        .pipe(publisher.publish(headers))
        // .pipe(publisher.sync())
        .pipe(awspublish.reporter());
};
```

**Comment by jarodtaylor** [comment]
Okay, so I'm thinking you can close this, because it's not an issue with gulp-awspublish. Gulp tasks just don't see/detect newly created files/folders. 

For anyone needing a solution, this is what I ended up doing, for now:

```
var gulp = require('gulp');
var runsequence = require('run-sequence');
var clean = require('gulp-clean');

gulp.task('metalsmith', require('./tasks/metalsmith'));
gulp.task('styles', require('./tasks/styles'));

gulp.task('clean', function() {
    return gulp.src('./build', {read: false})
        .pipe(clean());
});

gulp.task('build', function(cb){
    runsequence('clean', ['metalsmith', 'styles'], cb);
});

gulp.task('deploy', require('./tasks/deploy'));

```

So I broke the `build` and `deploy` tasks out so that I could now run this in my terminal:

```
gulp build && gulp deploy
```

I just added it to my `package.json` file:

```
{
  "scripts": {
    "deploy": "gulp build && gulp deploy"
  }
}
```

So now I can just use `npm run deploy` in my terminal.

It's the best I could come up with.

**Comment by pgherveou** [comment]
Sorry for the slow response, an thanks for the code snippets!
