### ISSUE TITLE
.sync() can only delete remote files within the first 1000 files

### ISSUE THREAD

**Issue by peruukki** [pgherveou/gulp-awspublish#93]
I noticed that some of our remote files were not deleted when using `.sync()`, and eventually found out that it's because the `sync` method enumerates the remote files with a simple call to [listObjects](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property) that only returns a maximum of 1000 files at a time.

I'm not sure how this should be solved, as [xml-json](https://github.com/maxogden/xml-json) is used for the XML to JSON conversion, and it doesn't seem to support converting the whole XML response tree. It looks like you'd need at least the `IsTruncated` and existing `Key` value from the response, but they don't fall under a common subtree.

**Comment by pgherveou** [comment]
```client.listObjects({ Prefix: prefix }).createReadStream()```

**Comment by daveplunkett** [comment]
Isn't it about time to fix this?

**Comment by rmoskal** [comment]
javascript is beginning to look like lisp with all the partially working projects.

**Comment by rmoskal** [comment]
There is now a PR that handles this:

https://github.com/pgherveou/gulp-awspublish/pull/175

If you can't wait it's here: https://github.com/rmoskal/gulp-awspublish

**Comment by pioug** [comment]
Fixed v4.1.0 https://github.com/pgherveou/gulp-awspublish/releases/tag/v4.1.0
