### ISSUE TITLE
set profile.

### ISSUE THREAD

**Issue by nathanredblur** [pgherveou/gulp-awspublish#97]
Hi, it's posible to set the profile to use?
I mean, when you configure your AWS client, you can set profiles.
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles

It's posible configure this inside awspublish?

**Comment by pgherveou** [comment]
I guess so 
Are you talking about what we mentioned here: https://github.com/pgherveou/gulp-awspublish#awspublishcreateoptions
Let us know if this works

**Comment by pgherveou** [comment]
closing the isssue for now feel free to reopen it

**Comment by nathanredblur** [comment]
yea, that exactly. thanks
