### ISSUE TITLE
Issue using Content-MD5

### ISSUE THREAD

**Issue by Fatalito** [pgherveou/gulp-awspublish#99]
Hi,

If you specify a header Content-MD5, it's passed though a pascal case conversion to become ContentMd5, but AWS is expecting ContentMD5 (uppercase D)

Error: 
UnexpectedParameter: Unexpected key 'ContentMd5' found in params.

Thanks!

**Comment by pgherveou** [comment]
Didnt know that
Would you mind sending me a Pull Request for that
you can add the exception around this line 
https://github.com/pgherveou/gulp-awspublish/blob/master/lib/index.js#L63

**Comment by Fatalito** [comment]
I created https://github.com/pgherveou/gulp-awspublish/pull/100/files

**Comment by RichardOtvos** [comment]
As this PR was merged in January (with #100, thanks for the PR @Fatalito ) and in the master branch since then, I'm just gonna close this ticket :)
